import { BOLD_ITALIC_STAR, BOLD_STAR, ITALIC_STAR, ORDERED_LIST, UNORDERED_LIST } from '@lexical/markdown'

export const MARKDOWN_TRANSFORMERS = [UNORDERED_LIST, ORDERED_LIST, BOLD_ITALIC_STAR, BOLD_STAR, ITALIC_STAR]
